version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252"
    networks:
      - softy-network
    deploy:
      replicas: 2

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: softy-pinko-frontend
    ports:
      - "9000"
    networks:
      - softy-network
    depends_on:
      - backend
    

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: softy-pinko-proxy
    ports:
      - "80:80"
    networks:
      - softy-network
    depends_on:
      - frontend
      - backend

networks:
  softy-network:
    driver: bridge
